fn main() {
    cause(Log("Hello World"))
    ExitCode(0)
}
